[package]
name = "fulgorart-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
fulgorart-core = { path = "../core" }
aws-sdk-s3 = "1"
aws-config = "1"
aws-credential-types = "1"
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
bytes = "1"
chrono = { workspace = true }
