[package]
name = "fulgorart-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fulgorart-web"
path = "src/main.rs"

[dependencies]
fulgorart-db = { path = "../db" }
fulgorart-storage = { path = "../storage" }
axum = { version = "0.7", features = ["macros"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
http = "1"
base64 = "0.22"
