[package]
name = "fulgorart-tagger"
version = "0.1.0"
edition = "2021"

[dependencies]
fulgorart-core = { path = "../core" }
fulgorart-db = { path = "../db" }
tokio = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
